//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GiaoVien_MonHoc
    {
        public int MaGV_MH { get; set; }
        public Nullable<int> MaGV { get; set; }
        public Nullable<int> MaNamHoc { get; set; }
        public Nullable<int> MaMH { get; set; }
        public string GhiChu { get; set; }
    }
}
