//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GiaoVien_Lop
    {
        public int MaGV_Lop { get; set; }
        public Nullable<int> MaGV { get; set; }
        public Nullable<int> MaLop { get; set; }
        public Nullable<int> MaNamHoc { get; set; }
        public Nullable<int> ChuNhiem { get; set; }
        public Nullable<int> MaMH { get; set; }
        public Nullable<int> MaHocKy { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual tb_GiaoVien tb_GiaoVien { get; set; }
        public virtual tb_HocKy tb_HocKy { get; set; }
        public virtual tb_Lop tb_Lop { get; set; }
        public virtual tb_NamHoc tb_NamHoc { get; set; }
    }
}
