//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HocSinh_Lop_NamHoc
    {
        public int MaHS { get; set; }
        public int MaLop { get; set; }
        public int MaNamHoc { get; set; }
        public int MaKhoiLop { get; set; }
    }
}
