//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ViPham_CT
    {
        public int MaVPCT { get; set; }
        public Nullable<int> MaViPham { get; set; }
        public Nullable<int> MaLoi { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<int> MaHS { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayViPham { get; set; }
    
        public virtual tb_DanhMucLoi tb_DanhMucLoi { get; set; }
        public virtual tb_HocSinh tb_HocSinh { get; set; }
        public virtual tb_ViPham tb_ViPham { get; set; }
    }
}
